// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: proto/objectpb/object.proto

package objectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	proto "server/proto"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HumanSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipe string `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Color  string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *HumanSlot) Reset() {
	*x = HumanSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanSlot) ProtoMessage() {}

func (x *HumanSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanSlot.ProtoReflect.Descriptor instead.
func (*HumanSlot) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{0}
}

func (x *HumanSlot) GetRecipe() string {
	if x != nil {
		return x.Recipe
	}
	return ""
}

func (x *HumanSlot) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type EquippedItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RightHand *ObjectWithVariation `protobuf:"bytes,1,opt,name=right_hand,json=rightHand,proto3" json:"right_hand,omitempty"`
	LeftHand  *ObjectWithVariation `protobuf:"bytes,2,opt,name=left_hand,json=leftHand,proto3" json:"left_hand,omitempty"`
}

func (x *EquippedItems) Reset() {
	*x = EquippedItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquippedItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquippedItems) ProtoMessage() {}

func (x *EquippedItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquippedItems.ProtoReflect.Descriptor instead.
func (*EquippedItems) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{1}
}

func (x *EquippedItems) GetRightHand() *ObjectWithVariation {
	if x != nil {
		return x.RightHand
	}
	return nil
}

func (x *EquippedItems) GetLeftHand() *ObjectWithVariation {
	if x != nil {
		return x.LeftHand
	}
	return nil
}

type HumanCharacter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gender string                `protobuf:"bytes,1,opt,name=gender,proto3" json:"gender,omitempty"`
	Slots  map[string]*HumanSlot `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HumanCharacter) Reset() {
	*x = HumanCharacter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanCharacter) ProtoMessage() {}

func (x *HumanCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanCharacter.ProtoReflect.Descriptor instead.
func (*HumanCharacter) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{2}
}

func (x *HumanCharacter) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *HumanCharacter) GetSlots() map[string]*HumanSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID      string          `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name      string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resource  string          `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Variation string          `protobuf:"bytes,4,opt,name=variation,proto3" json:"variation,omitempty"`
	Position  *proto.Vector3M `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Rotation  *proto.Vector3M `protobuf:"bytes,6,opt,name=rotation,proto3" json:"rotation,omitempty"`
	// Character or NPC settings
	Type           string          `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Speed          float32         `protobuf:"fixed32,8,opt,name=speed,proto3" json:"speed,omitempty"`
	Health         float32         `protobuf:"fixed32,9,opt,name=health,proto3" json:"health,omitempty"`
	IsSelf         bool            `protobuf:"varint,10,opt,name=is_self,json=isSelf,proto3" json:"is_self,omitempty"`
	HumanCharacter *HumanCharacter `protobuf:"bytes,11,opt,name=human_character,json=humanCharacter,proto3" json:"human_character,omitempty"`
	EquippedItems  *EquippedItems  `protobuf:"bytes,12,opt,name=equippedItems,proto3" json:"equippedItems,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{3}
}

func (x *Object) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Object) GetVariation() string {
	if x != nil {
		return x.Variation
	}
	return ""
}

func (x *Object) GetPosition() *proto.Vector3M {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Object) GetRotation() *proto.Vector3M {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *Object) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Object) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Object) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Object) GetIsSelf() bool {
	if x != nil {
		return x.IsSelf
	}
	return false
}

func (x *Object) GetHumanCharacter() *HumanCharacter {
	if x != nil {
		return x.HumanCharacter
	}
	return nil
}

func (x *Object) GetEquippedItems() *EquippedItems {
	if x != nil {
		return x.EquippedItems
	}
	return nil
}

type DestroyObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
}

func (x *DestroyObject) Reset() {
	*x = DestroyObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyObject) ProtoMessage() {}

func (x *DestroyObject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyObject.ProtoReflect.Descriptor instead.
func (*DestroyObject) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyObject) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type ObjectBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object []*Object `protobuf:"bytes,1,rep,name=object,proto3" json:"object,omitempty"`
}

func (x *ObjectBatch) Reset() {
	*x = ObjectBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectBatch) ProtoMessage() {}

func (x *ObjectBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectBatch.ProtoReflect.Descriptor instead.
func (*ObjectBatch) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectBatch) GetObject() []*Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type ObjectState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID         string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	VariantIndex int32  `protobuf:"varint,2,opt,name=variant_index,json=variantIndex,proto3" json:"variant_index,omitempty"`
}

func (x *ObjectState) Reset() {
	*x = ObjectState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectState) ProtoMessage() {}

func (x *ObjectState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectState.ProtoReflect.Descriptor instead.
func (*ObjectState) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectState) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ObjectState) GetVariantIndex() int32 {
	if x != nil {
		return x.VariantIndex
	}
	return 0
}

type ObjectStateBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectStates []*ObjectState `protobuf:"bytes,1,rep,name=object_states,json=objectStates,proto3" json:"object_states,omitempty"`
}

func (x *ObjectStateBatch) Reset() {
	*x = ObjectStateBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStateBatch) ProtoMessage() {}

func (x *ObjectStateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStateBatch.ProtoReflect.Descriptor instead.
func (*ObjectStateBatch) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectStateBatch) GetObjectStates() []*ObjectState {
	if x != nil {
		return x.ObjectStates
	}
	return nil
}

type ObjectWithVariation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource     string  `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Variation    string  `protobuf:"bytes,2,opt,name=variation,proto3" json:"variation,omitempty"`
	AttackRadius float32 `protobuf:"fixed32,3,opt,name=attack_radius,json=attackRadius,proto3" json:"attack_radius,omitempty"`
}

func (x *ObjectWithVariation) Reset() {
	*x = ObjectWithVariation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectWithVariation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectWithVariation) ProtoMessage() {}

func (x *ObjectWithVariation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectWithVariation.ProtoReflect.Descriptor instead.
func (*ObjectWithVariation) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectWithVariation) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ObjectWithVariation) GetVariation() string {
	if x != nil {
		return x.Variation
	}
	return ""
}

func (x *ObjectWithVariation) GetAttackRadius() float32 {
	if x != nil {
		return x.AttackRadius
	}
	return 0
}

type Damage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID          string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Amount        int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	HealthCurrent int32  `protobuf:"varint,3,opt,name=health_current,json=healthCurrent,proto3" json:"health_current,omitempty"`
	HealthMax     int32  `protobuf:"varint,4,opt,name=health_max,json=healthMax,proto3" json:"health_max,omitempty"`
	IsCrit        bool   `protobuf:"varint,5,opt,name=is_crit,json=isCrit,proto3" json:"is_crit,omitempty"`
}

func (x *Damage) Reset() {
	*x = Damage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_objectpb_object_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_objectpb_object_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_proto_objectpb_object_proto_rawDescGZIP(), []int{9}
}

func (x *Damage) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Damage) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Damage) GetHealthCurrent() int32 {
	if x != nil {
		return x.HealthCurrent
	}
	return 0
}

func (x *Damage) GetHealthMax() int32 {
	if x != nil {
		return x.HealthMax
	}
	return 0
}

func (x *Damage) GetIsCrit() bool {
	if x != nil {
		return x.IsCrit
	}
	return false
}

var File_proto_objectpb_object_proto protoreflect.FileDescriptor

var file_proto_objectpb_object_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x70, 0x62,
	0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x09, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x89, 0x01, 0x0a, 0x0d, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x70, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x3c, 0x0a, 0x0a, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x12, 0x3a, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x68,
	0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x69, 0x74, 0x68, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x65, 0x66, 0x74, 0x48, 0x61,
	0x6e, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x0e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x39, 0x0a,
	0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x1a, 0x4d, 0x0a, 0x0a, 0x53, 0x6c, 0x6f, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa7, 0x03, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x4d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x4d, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x6c,
	0x66, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x66, 0x12,
	0x41, 0x0a, 0x0f, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x52, 0x0e, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0d, 0x65, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x52, 0x0d, 0x65, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x23, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x22, 0x37, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x28, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22,
	0x46, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4e, 0x0a, 0x10, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x3a, 0x0a, 0x0d, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x22, 0x74, 0x0a, 0x13, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x6b, 0x5f, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0c, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x22, 0x93, 0x01,
	0x0a, 0x06, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4d, 0x61, 0x78, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73,
	0x5f, 0x63, 0x72, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x43,
	0x72, 0x69, 0x74, 0x42, 0x17, 0x5a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_objectpb_object_proto_rawDescOnce sync.Once
	file_proto_objectpb_object_proto_rawDescData = file_proto_objectpb_object_proto_rawDesc
)

func file_proto_objectpb_object_proto_rawDescGZIP() []byte {
	file_proto_objectpb_object_proto_rawDescOnce.Do(func() {
		file_proto_objectpb_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_objectpb_object_proto_rawDescData)
	})
	return file_proto_objectpb_object_proto_rawDescData
}

var file_proto_objectpb_object_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_objectpb_object_proto_goTypes = []interface{}{
	(*HumanSlot)(nil),           // 0: messages.HumanSlot
	(*EquippedItems)(nil),       // 1: messages.EquippedItems
	(*HumanCharacter)(nil),      // 2: messages.HumanCharacter
	(*Object)(nil),              // 3: messages.Object
	(*DestroyObject)(nil),       // 4: messages.DestroyObject
	(*ObjectBatch)(nil),         // 5: messages.ObjectBatch
	(*ObjectState)(nil),         // 6: messages.ObjectState
	(*ObjectStateBatch)(nil),    // 7: messages.ObjectStateBatch
	(*ObjectWithVariation)(nil), // 8: messages.ObjectWithVariation
	(*Damage)(nil),              // 9: messages.Damage
	nil,                         // 10: messages.HumanCharacter.SlotsEntry
	(*proto.Vector3M)(nil),      // 11: messages.Vector3M
}
var file_proto_objectpb_object_proto_depIdxs = []int32{
	8,  // 0: messages.EquippedItems.right_hand:type_name -> messages.ObjectWithVariation
	8,  // 1: messages.EquippedItems.left_hand:type_name -> messages.ObjectWithVariation
	10, // 2: messages.HumanCharacter.slots:type_name -> messages.HumanCharacter.SlotsEntry
	11, // 3: messages.Object.position:type_name -> messages.Vector3M
	11, // 4: messages.Object.rotation:type_name -> messages.Vector3M
	2,  // 5: messages.Object.human_character:type_name -> messages.HumanCharacter
	1,  // 6: messages.Object.equippedItems:type_name -> messages.EquippedItems
	3,  // 7: messages.ObjectBatch.object:type_name -> messages.Object
	6,  // 8: messages.ObjectStateBatch.object_states:type_name -> messages.ObjectState
	0,  // 9: messages.HumanCharacter.SlotsEntry.value:type_name -> messages.HumanSlot
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_objectpb_object_proto_init() }
func file_proto_objectpb_object_proto_init() {
	if File_proto_objectpb_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_objectpb_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquippedItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanCharacter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStateBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectWithVariation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_objectpb_object_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Damage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_objectpb_object_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_objectpb_object_proto_goTypes,
		DependencyIndexes: file_proto_objectpb_object_proto_depIdxs,
		MessageInfos:      file_proto_objectpb_object_proto_msgTypes,
	}.Build()
	File_proto_objectpb_object_proto = out.File
	file_proto_objectpb_object_proto_rawDesc = nil
	file_proto_objectpb_object_proto_goTypes = nil
	file_proto_objectpb_object_proto_depIdxs = nil
}
