// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: proto/transformpb/transform.proto

package transformpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	proto "server/proto"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID     string          `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Speed    float32         `protobuf:"fixed32,2,opt,name=speed,proto3" json:"speed,omitempty"`
	Position *proto.Vector3M `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation *proto.Vector3M `protobuf:"bytes,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
}

func (x *Transform) Reset() {
	*x = Transform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_transformpb_transform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transformpb_transform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_proto_transformpb_transform_proto_rawDescGZIP(), []int{0}
}

func (x *Transform) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Transform) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Transform) GetPosition() *proto.Vector3M {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Transform) GetRotation() *proto.Vector3M {
	if x != nil {
		return x.Rotation
	}
	return nil
}

type TransformRotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID     string          `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Rotation *proto.Vector3M `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
}

func (x *TransformRotation) Reset() {
	*x = TransformRotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_transformpb_transform_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformRotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRotation) ProtoMessage() {}

func (x *TransformRotation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transformpb_transform_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRotation.ProtoReflect.Descriptor instead.
func (*TransformRotation) Descriptor() ([]byte, []int) {
	return file_proto_transformpb_transform_proto_rawDescGZIP(), []int{1}
}

func (x *TransformRotation) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *TransformRotation) GetRotation() *proto.Vector3M {
	if x != nil {
		return x.Rotation
	}
	return nil
}

type Teleport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID     string          `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Position *proto.Vector3M `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation *proto.Vector3M `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
}

func (x *Teleport) Reset() {
	*x = Teleport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_transformpb_transform_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teleport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teleport) ProtoMessage() {}

func (x *Teleport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transformpb_transform_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teleport.ProtoReflect.Descriptor instead.
func (*Teleport) Descriptor() ([]byte, []int) {
	return file_proto_transformpb_transform_proto_rawDescGZIP(), []int{2}
}

func (x *Teleport) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Teleport) GetPosition() *proto.Vector3M {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Teleport) GetRotation() *proto.Vector3M {
	if x != nil {
		return x.Rotation
	}
	return nil
}

var File_proto_transformpb_transform_proto protoreflect.FileDescriptor

var file_proto_transformpb_transform_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x70, 0x62, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x12, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x95, 0x01, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x4d, 0x52,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x4d, 0x52,
	0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x57, 0x0a, 0x11, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x4d, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x7e, 0x0a, 0x08, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x4d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x4d, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_transformpb_transform_proto_rawDescOnce sync.Once
	file_proto_transformpb_transform_proto_rawDescData = file_proto_transformpb_transform_proto_rawDesc
)

func file_proto_transformpb_transform_proto_rawDescGZIP() []byte {
	file_proto_transformpb_transform_proto_rawDescOnce.Do(func() {
		file_proto_transformpb_transform_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_transformpb_transform_proto_rawDescData)
	})
	return file_proto_transformpb_transform_proto_rawDescData
}

var file_proto_transformpb_transform_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_transformpb_transform_proto_goTypes = []interface{}{
	(*Transform)(nil),         // 0: messages.Transform
	(*TransformRotation)(nil), // 1: messages.TransformRotation
	(*Teleport)(nil),          // 2: messages.Teleport
	(*proto.Vector3M)(nil),    // 3: messages.Vector3M
}
var file_proto_transformpb_transform_proto_depIdxs = []int32{
	3, // 0: messages.Transform.position:type_name -> messages.Vector3M
	3, // 1: messages.Transform.rotation:type_name -> messages.Vector3M
	3, // 2: messages.TransformRotation.rotation:type_name -> messages.Vector3M
	3, // 3: messages.Teleport.position:type_name -> messages.Vector3M
	3, // 4: messages.Teleport.rotation:type_name -> messages.Vector3M
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_transformpb_transform_proto_init() }
func file_proto_transformpb_transform_proto_init() {
	if File_proto_transformpb_transform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_transformpb_transform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_transformpb_transform_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformRotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_transformpb_transform_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teleport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_transformpb_transform_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_transformpb_transform_proto_goTypes,
		DependencyIndexes: file_proto_transformpb_transform_proto_depIdxs,
		MessageInfos:      file_proto_transformpb_transform_proto_msgTypes,
	}.Build()
	File_proto_transformpb_transform_proto = out.File
	file_proto_transformpb_transform_proto_rawDesc = nil
	file_proto_transformpb_transform_proto_goTypes = nil
	file_proto_transformpb_transform_proto_depIdxs = nil
}
